service: serverless-webpack-typescript-example

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-kubeless

provider:
  name: kubeless
  runtime: nodejs6

functions:
  hello:
    handler: handler.hello
