service: serverless-kubeless-webpack-typescript-example

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-kubeless

package:
  individually: true

provider:
  name: kubeless
  runtime: nodejs6

functions:
  hello:
    handler: handler.hello
    package: ./.serverless/hello.zip
